title: Jane Hsieh
subtitle: Research assistant at <a href="https://www.cmu.edu/">Carnegie Mellon University</a>
description: >- # this means to ignore newlines until "baseurl:"
  This is a site about Jane!
baseurl: "" # the subpath of your site, e.g. /blog
url: "janeon.github.io" # the base hostname & protocol for your site, e.g. http://example.com

author_logo: profile.png
author:  janeon
author_bio: >
  I am a second year <a href="http://se-phd.isri.cmu.edu/People/students/index.html">Software Engineering PhD candidate</a> at the <a href="https://www.isri.cmu.edu/">Institute of Software Research</a> 
  advised by <a href="https://haiyizhu.com/">Professor Haiyi Zhu</a> from the 
  <a href="https://hcii.cmu.edu/"> Human Computer Interaction Institute </a>. 
  I work in the area of sociotechnical research and my current projects focus on (1) identifying gig worker communication strategies (2) toxicity moderation and bot usage by open source maintainers and (3) identifying and improving early gig worker dropoff.
  If you're interested in similar research, check out the <a href="https://www.hcii.cmu.edu/research/social-computing-lab">Social Computing Lab</a> or reach out to me with questions via the contact info on the right. Let's keep in touch!
author_email: "janeon@cmu.edu"
author_location:  Pittsburgh, PA
author_website_url:  "CV"
author_resume: "Resume"


# social links
twitter_username: JaneHsieh9
github_username:  janeon
facebook_username: jwhsieh98
linkedin_username: jane-hsieh
behance_username: yourusername
instagram_username: janeon32
medium_username: yourusername
telegram_username: yourusername
dribbble_username: yourusername
flickr_username: yourusername

plugins:
  - jekyll/scholar

scholar:
  source: ./bibliography
  bibliography: sample.bib
