title: Jane Hsieh
subtitle: Researcher, frontend engineer and an aspiring user researcher
description: >- # this means to ignore newlines until "baseurl:"
  This is a site about Jane!
baseurl: "" # the subpath of your site, e.g. /blog
url: "janeon.github.io" # the base hostname & protocol for your site, e.g. http://example.com

author_logo: profile.png
author:  janeon
author_bio: >
  I am a first year PhD candidate in Software Engineering with a passion for diversity and inclusivity social coding platforms
  <br></br> I also have a huge crush on HCI research and UX/UI design
  <br></br> Check out my projects and research publications above and let's keep in touch!
author_email: "jhsieh2@andrew.cmu.edu"
author_location:  Pittsburgh, PA
author_website_url:  "CV"
author_resume: "Resume"


# social links
twitter_username: JaneHsieh9
github_username:  janeon
facebook_username: jwhsieh98
linkedin_username: jane-hsieh
behance_username: yourusername
instagram_username: janeon32
medium_username: yourusername
telegram_username: yourusername
dribbble_username: yourusername
flickr_username: yourusername

plugins:
  - jekyll/scholar

scholar:
  source: ./bibliography
  bibliography: sample.bib
