title: Jane Hsieh
subtitle: Undergraduate Researcher at Oberlin College
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "janeon.github.io" # the base hostname & protocol for your site, e.g. http://example.com

author_logo: profile.png
author:  janeon
author_bio: Hi there, thanks for visiting. <br></br> I'm a recent graduate of Oberlin College with majors in compter science, math and a concentration in cognitive science. <br></br> Check out my project repos and research publications. Let's keep in touch!
author_email: "jhsieh2@andrew.cmu.edu"
author_location:  Oberlin, Ohio
author_website_url:  "CV"
author_resume: "Resume"


# social links
twitter_username: yourusername
github_username:  janeon
facebook_username: jwhsieh98
linkedin_username: jane-hsieh
behance_username: yourusername
instagram_username: janeon32
medium_username: yourusername
telegram_username: yourusername
dribbble_username: yourusername
flickr_username: yourusername
